##
# Copyright (c) 2026 Oleksii Serdiuk
# SPDX-License-Identifier: BSD-3-Clause
##

component_management:
  individual_components:
    - component_id: core
      name: Core
      paths:
        - src/core/**
    - component_id: format_plugins
      name: Format Plugins
      paths:
        - src/formats/**
    - component_id: data_providers
      name: Data Providers
      paths:
        - src/data-providers/**

coverage:
  range: "75..90"
  status:
    project:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "condensed_header, diff, components, condensed_files, condensed_footer"
