##
# Copyright (c) 2026 Oleksii Serdiuk
# SPDX-License-Identifier: BSD-3-Clause
##

# SonarQube Configuration
sonar.organization=leppa
sonar.projectKey=convert-to-wealthfolio
sonar.projectName=Convert to Wealthfolio
sonar.projectVersion=0.2.0

# Source configuration
sonar.sources=src,.github
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/**/index.ts

# Coverage reports
sonar.javascript.lcov.reportPaths=./test-results/lcov.info
