##
# Copyright (c) 2026 Oleksii Serdiuk
# SPDX-License-Identifier: BSD-3-Clause
##

name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: Build and test with the latest LTS Node.js version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      package_file: ${{ steps.create_npm_package.outputs.package_file }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Update npm and install dependencies
        run: |
          npm install --ignore-scripts -g npm@latest
          npm ci --ignore-scripts

      - name: Check linting & formatting
        run: |
          npm run lint:check
          npm run format:check

      - name: Patch package version
        # Double dash (`--`) is to rank these builds even lower than pre-relese tags like `alpha`
        run: npm pkg set version="$(jq --raw-output .version package.json)--ci.${{ github.run_number }}.${{ github.run_attempt }}+git.$(git rev-parse --short HEAD)"

      - name: Build code
        run: npm run build

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Create npm package
        id: create_npm_package
        # `npm pack` prints the name of the created file on `stdout`, so we
        # capture it to use it in the upload step
        run: echo "package_file=$(npm pack)" >> "$GITHUB_OUTPUT"

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report.zip
          path: coverage/

      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.create_npm_package.outputs.package_file }}
          # Already compressed by `npm pack`
          archive: false

  test-supported-node-versions:
    name: Test with supported Node.js versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build-and-test
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x, 25.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test

  run-sonarqube-analysis:
    name: Run SonarQube analysis
    needs: build-and-test
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/sonarqube-analysis.yml
    secrets:
      SONARQUBE_ACCESS_TOKEN: ${{ secrets.SONARQUBE_ACCESS_TOKEN }}

  publish-to-github-packages:
    name: Publish to GitHub Packages
    needs: build-and-test
    # Only trigger for the `main` and `dev` branches
    if: ${{ github.ref_name == 'main' || github.ref_name == 'dev' }}
    permissions:
      actions: read
      contents: read
      packages: write
    uses: ./.github/workflows/publish-to-github-packages.yml
    with:
      artifact_name: ${{ needs.build-and-test.outputs.package_file }}
      tag: ci-${{ github.ref_name }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
