##
# Copyright (c) 2026 Oleksii Serdiuk
# SPDX-License-Identifier: BSD-3-Clause
##

name: Publish to GitHub Packages

on:
  workflow_call:
    inputs:
      artifact_name:
        description: Name of the artifact containing the npm package
        type: string
        required: true
    secrets:
      NODE_AUTH_TOKEN:
        description: Token with write permission to GitHub Packages
        required: true

jobs:
  publish-to-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          registry-url: https://npm.pkg.github.com
          scope: "@${{ github.repository_owner }}"

      - name: Update npm
        run: npm install --ignore-scripts -g npm@latest

      - name: Pull package artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact_name }}
          # Uploaded with `archive: false`
          skip-decompress: true

      - name: Publish package to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm publish ./*convert-to-wealthfolio*.tgz --tag ci-main
