##
# Copyright (c) 2026 Oleksii Serdiuk
# SPDX-License-Identifier: BSD-3-Clause
##

name: SonarQube Analysis

on:
  workflow_call:
    secrets:
      SONARQUBE_ACCESS_TOKEN:
        description: SonarQube Access Token
        required: true

jobs:
  run-sonarqube-analysis:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download test results artifact
        uses: actions/download-artifact@v8
        with:
          name: test-results.zip
          path: test-results/

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_ACCESS_TOKEN }}
